package app.alcada.consulta;
import static io.restassured.RestAssured.given;import static org.hamcrest.Matchers.*;import static org.junit.jupiter.api.Assertions.assertEquals;
import java.util.UUID;import io.quarkus.narayana.jta.QuarkusTransaction;import io.quarkus.test.junit.QuarkusTest;import jakarta.inject.Inject;import jakarta.persistence.EntityManager;import org.junit.jupiter.api.Test;
@QuarkusTest class ItensTest {@Inject EntityManager em;
 @Test void c1_busca_titulo_aberta_ou_fechada(){Ctx c=novo();pend(c,"Contrato Alfa","FECHADA",null,null);given().header("X-Org-Id",c.org).queryParam("q","contrato Alfa").get("/v1/itens").then().statusCode(200).body("total",equalTo(1)).body("itens[0].status",equalTo("FECHADA"));}
 @Test void c2_filtra_pessoa_e_busca_executor(){Ctx c=novo();UUID carolina=pessoa(c,"Carolina");UUID p=pend(c,"Aprovar", "DELEGADA",null,null);deleg(c,p,carolina,"N2");given().header("X-Org-Id",c.org).queryParam("pessoaId",carolina).get("/v1/itens").then().body("total",equalTo(1)).body("itens[0].executor",equalTo("Carolina"));given().header("X-Org-Id",c.org).queryParam("q","Carolina").get("/v1/itens").then().body("total",equalTo(1));}
 @Test void c3_filtra_decisoes_fechadas_no_periodo(){Ctx c=novo();pend(c,"Decisão semanal","FECHADA",null,null);given().header("X-Org-Id",c.org).queryParam("classe","DECISAO").queryParam("status","FECHADA").queryParam("de",java.time.OffsetDateTime.now().minusDays(7).toString()).queryParam("ate",java.time.OffsetDateTime.now().plusMinutes(1).toString()).get("/v1/itens").then().body("total",equalTo(1)).body("itens[0].titulo",equalTo("Decisão semanal"));}
 @Test void c4_n2_aberto_nao_mistura(){Ctx c=novo();UUID dono=pessoa(c,"Exec");UUID a=pend(c,"N2 aberto","DELEGADA",null,null),b=pend(c,"N1 aberto","DELEGADA",null,null),f=pend(c,"N2 fechado","FECHADA",null,null);deleg(c,a,dono,"N2");deleg(c,b,dono,"N1");deleg(c,f,dono,"N2");given().header("X-Org-Id",c.org).queryParam("nivel","N2").queryParam("status","DELEGADA").get("/v1/itens").then().body("total",equalTo(1)).body("itens[0].titulo",equalTo("N2 aberto"));}
 @Test void c5_busca_origem_reconhecivel(){Ctx c=novo();pend(c,"Imposto","ENTRADA","grupo-fiscal","Fiscal");given().header("X-Org-Id",c.org).queryParam("origem","Fiscal").get("/v1/itens").then().body("total",equalTo(1)).body("itens[0].origem",equalTo("Fiscal"));}
 @Test void c6_abertas_e_fechadas_coexistem(){Ctx c=novo();pend(c,"Aberta","ENTRADA",null,null);pend(c,"Fechada","FECHADA",null,null);given().header("X-Org-Id",c.org).get("/v1/itens").then().body("total",equalTo(2)).body("itens.status",hasItems("ENTRADA","FECHADA"));}
 @Test void c7_detalhe_traz_historia(){Ctx c=novo();UUID p=pend(c,"História","ENTRADA",null,null);trilha(c,p);given().header("X-Org-Id",c.org).get("/v1/itens/"+p).then().statusCode(200).body("trilha[0].tipo",equalTo("CAPTADA"));}
 @Test void c8_links_profundos_sao_deterministicos(){Ctx c=novo();UUID dono=pessoa(c,"Responsável");UUID p=pend(c,"Com destino","DELEGADA",null,null);deleg(c,p,dono,"N2");given().header("X-Org-Id",c.org).get("/v1/itens/"+p).then().body("item.links.tipo",hasItems("TRILHA","DELEGACAO","BLOCO"));}
 @Test void c9_termo_apenas_no_bruto_nao_e_pesquisavel(){Ctx c=novo();pend(c,"Título público","ENTRADA",null,null);bruto(c,"segredo-retido-987");given().header("X-Org-Id",c.org).queryParam("q","segredo-retido-987").get("/v1/itens").then().body("total",equalTo(0));}
 @Test void c10_paginacao_limitada(){Ctx c=novo();given().header("X-Org-Id",c.org).queryParam("tamanho",101).get("/v1/itens").then().statusCode(422);}
 @Test void c11_isolamento(){Ctx a=novo(),b=novo();UUID segredo=pend(b,"Segredo","ENTRADA",null,null);given().header("X-Org-Id",a.org).queryParam("q","Segredo").get("/v1/itens").then().body("total",equalTo(0));given().header("X-Org-Id",a.org).get("/v1/itens/"+segredo).then().statusCode(404);}
 @Test void volume_sintetico_mantem_pagina_limitada(){Ctx c=novo();QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO pendencia(id,org_id,titulo,classe,horizonte,status) SELECT gen_random_uuid(),?,'Item volume '||n,'DECISAO','SEMANA','ENTRADA' FROM generate_series(1,1000) n").setParameter(1,c.org).executeUpdate());given().header("X-Org-Id",c.org).queryParam("pagina",9).queryParam("tamanho",100).get("/v1/itens").then().statusCode(200).body("total",equalTo(1000)).body("itens",hasSize(100));}
 private Ctx novo(){UUID o=UUID.randomUUID();QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO organizacao(id,nome) VALUES (?,'Org')").setParameter(1,o).executeUpdate());return new Ctx(o);}
 private UUID pessoa(Ctx c,String n){UUID id=UUID.randomUUID();QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO pessoa(id,org_id,nome) VALUES (?,?,?)").setParameter(1,id).setParameter(2,c.org).setParameter(3,n).executeUpdate());return id;}
 private UUID pend(Ctx c,String t,String s,String thread,String grupo){UUID id=UUID.randomUUID();QuarkusTransaction.requiringNew().run(()->{em.createNativeQuery("INSERT INTO pendencia(id,org_id,titulo,classe,horizonte,status,origem_thread) VALUES (?,?,?,'DECISAO','SEMANA',?,?)").setParameter(1,id).setParameter(2,c.org).setParameter(3,t).setParameter(4,s).setParameter(5,thread).executeUpdate();if(grupo!=null){UUID f=UUID.randomUUID();em.createNativeQuery("INSERT INTO fonte(id,org_id,tipo,identificador,segredo) VALUES (?,?,'WHATSAPP','canal','s')").setParameter(1,f).setParameter(2,c.org).executeUpdate();em.createNativeQuery("INSERT INTO grupo_acompanhado(org_id,fonte_id,grupo_id,nome) VALUES (?,?,?,?)").setParameter(1,c.org).setParameter(2,f).setParameter(3,thread).setParameter(4,grupo).executeUpdate();em.createNativeQuery("INSERT INTO evento_bruto(id,org_id,fonte_id,mensagem_id,thread_ref,expira_em) VALUES (?,?,?,?,?,now()+interval '1 day')").setParameter(1,UUID.randomUUID()).setParameter(2,c.org).setParameter(3,f).setParameter(4,UUID.randomUUID().toString()).setParameter(5,thread).executeUpdate();}});return id;}
 private void deleg(Ctx c,UUID p,UUID dono,String n){QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO delegacao(id,org_id,pendencia_id,dono_id,nivel,prazo,janela,escalonamento) VALUES (?,?,?,?,?,now()+interval '1 day',interval '4 hours',interval '1 day')").setParameter(1,UUID.randomUUID()).setParameter(2,c.org).setParameter(3,p).setParameter(4,dono).setParameter(5,n).executeUpdate());}
 private void trilha(Ctx c,UUID p){QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO trilha(org_id,pendencia_id,tipo,ator) VALUES (?,?,'CAPTADA','SISTEMA:motor:teste')").setParameter(1,c.org).setParameter(2,p).executeUpdate());}
 private void bruto(Ctx c,String texto){QuarkusTransaction.requiringNew().run(()->{UUID f=UUID.randomUUID();em.createNativeQuery("INSERT INTO fonte(id,org_id,tipo,identificador,segredo) VALUES (?,?,'EMAIL','origem','s')").setParameter(1,f).setParameter(2,c.org).executeUpdate();em.createNativeQuery("INSERT INTO evento_bruto(id,org_id,fonte_id,mensagem_id,texto,expira_em) VALUES (?,?,?,?,?,now()+interval '1 day')").setParameter(1,UUID.randomUUID()).setParameter(2,c.org).setParameter(3,f).setParameter(4,UUID.randomUUID().toString()).setParameter(5,texto).executeUpdate();});}
 private record Ctx(UUID org){}
}
