package app.alcada.notificacao.internal;

import java.net.URI;import java.net.http.*;import java.nio.charset.StandardCharsets;import java.security.*;import java.security.spec.PKCS8EncodedKeySpec;import java.time.Instant;import java.util.*;
import com.fasterxml.jackson.databind.*;import app.alcada.plataforma.cripto.port.Cofre;import app.alcada.plataforma.multitenancy.port.OrgId;import jakarta.enterprise.context.ApplicationScoped;import jakarta.persistence.EntityManager;import org.eclipse.microprofile.config.inject.ConfigProperty;
import org.jboss.logging.Logger;

@ApplicationScoped
public class FirebasePush {
 private static final Logger LOG=Logger.getLogger(FirebasePush.class);
 private final EntityManager em;private final ObjectMapper json;private final String credencial;private final Cofre cofre;private final HttpClient http=HttpClient.newHttpClient();private String acesso;private long expira;
 public FirebasePush(EntityManager em,ObjectMapper json,@ConfigProperty(name="firebase.service-account-base64") Optional<String> credencial,Cofre cofre){this.em=em;this.json=json;this.credencial=credencial.filter(v->!v.isBlank()).map(v->new String(Base64.getDecoder().decode(v),StandardCharsets.UTF_8)).orElse("");this.cofre=cofre;}
 public void enviar(OrgId org,UUID pessoa,String titulo,String corpo,String delegacao){if(credencial.isBlank())return;@SuppressWarnings("unchecked") List<String> rs=em.createNativeQuery("SELECT token_cifrado FROM dispositivo_push WHERE org_id=? AND pessoa_id=?").setParameter(1,org.valor()).setParameter(2,pessoa).getResultList();for(String c:rs)try{enviarToken(cofre.decifrar(c),titulo,corpo,delegacao);}catch(Exception e){LOG.warnf(e,"Falha ao enviar push da delegacao %s",delegacao);}}
 private void enviarToken(String token,String titulo,String corpo,String delegacao)throws Exception{JsonNode cfg=json.readTree(credencial);String projeto=cfg.path("project_id").asText();String payload=json.writeValueAsString(Map.of("message",Map.of("token",token,"notification",Map.of("title",titulo,"body",corpo),"data",Map.of("delegacaoId",delegacao,"link","https://alcada.vendax.ai/app/delegacoes/"+delegacao))));HttpRequest r=HttpRequest.newBuilder(URI.create("https://fcm.googleapis.com/v1/projects/"+projeto+"/messages:send")).header("Authorization","Bearer "+acesso(cfg)).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(payload)).build();HttpResponse<String> res=http.send(r,HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new IllegalStateException("FCM respondeu HTTP "+res.statusCode());}
 private synchronized String acesso(JsonNode c)throws Exception{long agora=Instant.now().getEpochSecond();if(acesso!=null&&agora<expira-60)return acesso;String h=b64("{\"alg\":\"RS256\",\"typ\":\"JWT\"}".getBytes());String claims=json.writeValueAsString(Map.of("iss",c.path("client_email").asText(),"scope","https://www.googleapis.com/auth/firebase.messaging","aud","https://oauth2.googleapis.com/token","iat",agora,"exp",agora+3600));String base=h+"."+b64(claims.getBytes());Signature s=Signature.getInstance("SHA256withRSA");s.initSign(chave(c.path("private_key").asText()));s.update(base.getBytes(StandardCharsets.UTF_8));String jwt=base+"."+b64(s.sign());String form="grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion="+java.net.URLEncoder.encode(jwt,StandardCharsets.UTF_8);HttpResponse<String> res=http.send(HttpRequest.newBuilder(URI.create("https://oauth2.googleapis.com/token")).header("Content-Type","application/x-www-form-urlencoded").POST(HttpRequest.BodyPublishers.ofString(form)).build(),HttpResponse.BodyHandlers.ofString());if(res.statusCode()/100!=2)throw new IllegalStateException("OAuth Google respondeu HTTP "+res.statusCode());JsonNode j=json.readTree(res.body());acesso=j.path("access_token").asText();if(acesso.isBlank())throw new IllegalStateException("OAuth Google não devolveu access_token");expira=agora+j.path("expires_in").asLong(3600);return acesso;}
 private static PrivateKey chave(String pem)throws Exception{byte[] b=Base64.getMimeDecoder().decode(pem.replace("-----BEGIN PRIVATE KEY-----","").replace("-----END PRIVATE KEY-----",""));return KeyFactory.getInstance("RSA").generatePrivate(new PKCS8EncodedKeySpec(b));}private static String b64(byte[] b){return Base64.getUrlEncoder().withoutPadding().encodeToString(b);}
}
