package app.alcada.metricas;
import static io.restassured.RestAssured.given;import static org.hamcrest.Matchers.*;import static org.junit.jupiter.api.Assertions.*;
import java.util.*;import io.quarkus.narayana.jta.QuarkusTransaction;import io.quarkus.test.junit.QuarkusTest;import jakarta.inject.Inject;import jakarta.persistence.EntityManager;import org.junit.jupiter.api.Test;

@QuarkusTest class SessaoRevisaoTest {@Inject EntityManager em;
 @Test void c1_sessao_e_idempotente(){Ctx c=novo();pend(c,"Na entrada","ENTRADA","SEMANA");String a=iniciar(c),b=iniciar(c);assertEquals(a,b);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+a).then().statusCode(200).body("revisao.entrada.qtd",equalTo(1));}
 @Test void c1_corrida_de_inicio_devolve_uma_sessao(){Ctx c=novo();try(var pool=java.util.concurrent.Executors.newFixedThreadPool(2)){var a=pool.submit(()->iniciar(c));var b=pool.submit(()->iniciar(c));assertEquals(a.get(),b.get());}catch(Exception e){throw new RuntimeException(e);}assertEquals(1L,num("SELECT count(*) FROM sessao_revisao WHERE org_id=? AND status='ABERTA'",c.org));}
 @Test void c2_entrada_e_triadas_dentro_do_roteiro(){Ctx c=novo();UUID p=pend(c,"Decidir agora","ENTRADA","SEMANA");String id=iniciar(c);given().headers(h(c)).contentType("application/json").body("{}").post("/v1/pendencias/"+p+"/resolver").then().statusCode(204);given().headers(h(c)).post("/v1/revisao-semanal/sessoes/"+id+"/concluir").then().body("resumo.dependenciasRemovidas",equalTo(1)).body("resumo.fechadas",equalTo(1));}
 @Test void c3_adiado_recorrente_tem_fonte(){Ctx c=novo();UUID p=pend(c,"Voltou outra vez","ENTRADA","SEMANA");QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("UPDATE pendencia SET adiado_count=3 WHERE org_id=? AND id=?").setParameter(1,c.org).setParameter(2,p).executeUpdate());String id=iniciar(c);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+id).then().body("revisao.adiados[0].id",equalTo(p.toString()));}
 @Test void c4_regra_observada_exige_evidencia_e_grava_trilha(){Ctx c=novo();for(int n=0;n<3;n++){UUID p=pend(c,"Caso "+n,"FECHADA","SEMANA");delegExecutada(c,p,"N2");evento(c,p,"RESOLVIDA");}String id=iniciar(c);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+id).then().body("propostas.classe",hasItem("DECISAO"));given().headers(h(c)).post("/v1/revisao-semanal/sessoes/"+id+"/regras/DECISAO/observar").then().statusCode(204);assertEquals(1L,num("SELECT count(*) FROM trilha WHERE org_id=? AND tipo='SUGESTAO_OBSERVADA'",c.org));assertEquals(0L,num("SELECT count(*) FROM regra_autonomia WHERE org_id=? AND ativa",c.org));}
 @Test void c5_promocao_conservadora_exige_confirmacao(){Ctx c=novo();for(int n=0;n<3;n++){UUID p=pend(c,"N3 "+n,"FECHADA","SEMANA");delegExecutada(c,p,"N3");}String id=iniciar(c);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+id).then().body("candidatasNivel[0].nivelSugerido",equalTo("N2"));given().headers(h(c)).contentType("application/json").body("{\"classe\":\"DECISAO\",\"donoId\":\""+c.gestor+"\",\"nivelAtual\":\"N3\"}").post("/v1/revisao-semanal/sessoes/"+id+"/promocoes").then().statusCode(204);assertEquals(1L,num("SELECT count(*) FROM regra_autonomia WHERE org_id=? AND nivel='N2' AND ativa",c.org));}
 @Test void c6_evidencia_insuficiente_nao_promove(){Ctx c=novo();for(int n=0;n<2;n++){UUID p=pend(c,"Pouco "+n,"FECHADA","SEMANA");delegExecutada(c,p,"N3");}String id=iniciar(c);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+id).then().body("candidatasNivel",empty());given().headers(h(c)).contentType("application/json").body("{\"classe\":\"DECISAO\",\"donoId\":\""+c.gestor+"\",\"nivelAtual\":\"N3\"}").post("/v1/revisao-semanal/sessoes/"+id+"/promocoes").then().statusCode(422);}
 @Test void c7_trimestre_so_protege_apos_confirmacao_e_deduplica(){Ctx c=novo();pend(c,"Planejamento","ENTRADA","TRIMESTRE");String id=iniciar(c);given().headers(h(c)).get("/v1/revisao-semanal/sessoes/"+id).then().body("trimestre.quantidade",equalTo(1));assertEquals(0L,num("SELECT count(*) FROM outbox WHERE org_id=?",c.org));String body="{\"inicio\":\""+java.time.OffsetDateTime.now().plusDays(2)+"\",\"duracaoMinutos\":120}";String a=given().headers(h(c)).contentType("application/json").body(body).post("/v1/revisao-semanal/sessoes/"+id+"/protecao-agenda").then().statusCode(201).extract().path("id"),b=given().headers(h(c)).contentType("application/json").body(body).post("/v1/revisao-semanal/sessoes/"+id+"/protecao-agenda").then().statusCode(201).extract().path("id");assertEquals(a,b);assertEquals(1L,num("SELECT count(*) FROM outbox WHERE org_id=? AND tipo='PROTECAO_AGENDA'",c.org));}
 @Test void c8_c9_fechamento_mede_reducao_e_nomeia_improdutiva(){Ctx c=novo();pend(c,"Ainda depende","ENTRADA","SEMANA");String id=iniciar(c);given().headers(h(c)).post("/v1/revisao-semanal/sessoes/"+id+"/concluir").then().statusCode(200).body("resumo.dependenciasRemovidas",equalTo(0)).body("resumo.continuamDependendo",equalTo(1)).body("resumo.improdutiva",equalTo(true));}
 @Test void c10_concluir_repetido_e_estavel(){Ctx c=novo();String id=iniciar(c);String a=given().headers(h(c)).post("/v1/revisao-semanal/sessoes/"+id+"/concluir").asString(),b=given().headers(h(c)).post("/v1/revisao-semanal/sessoes/"+id+"/concluir").asString();assertEquals(a,b);}
 @Test void c11_isolamento_por_organizacao(){Ctx a=novo(),b=novo();String id=iniciar(b);given().headers(h(a)).get("/v1/revisao-semanal/sessoes/"+id).then().statusCode(404);}
 private String iniciar(Ctx c){return given().headers(h(c)).post("/v1/revisao-semanal/sessoes").then().statusCode(anyOf(is(200),is(201))).extract().path("id");}
 private Ctx novo(){UUID o=UUID.randomUUID(),g=UUID.randomUUID();QuarkusTransaction.requiringNew().run(()->{em.createNativeQuery("INSERT INTO organizacao(id,nome) VALUES (?,'Org')").setParameter(1,o).executeUpdate();em.createNativeQuery("INSERT INTO pessoa(id,org_id,nome) VALUES (?,?,'Gestor')").setParameter(1,g).setParameter(2,o).executeUpdate();});return new Ctx(o,g);}
 private UUID pend(Ctx c,String titulo,String status,String horizonte){UUID id=UUID.randomUUID();QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO pendencia(id,org_id,titulo,classe,horizonte,status) VALUES (?,? ,?,'DECISAO',?,?)").setParameter(1,id).setParameter(2,c.org).setParameter(3,titulo).setParameter(4,horizonte).setParameter(5,status).executeUpdate());return id;}
 private void delegExecutada(Ctx c,UUID p,String nivel){QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO delegacao(id,org_id,pendencia_id,dono_id,nivel,prazo,janela,escalonamento,status) VALUES (?,?,?,?,?,now(),interval '1 hour',interval '1 day','EXECUTADA')").setParameter(1,UUID.randomUUID()).setParameter(2,c.org).setParameter(3,p).setParameter(4,c.gestor).setParameter(5,nivel).executeUpdate());}
 private void evento(Ctx c,UUID p,String tipo){QuarkusTransaction.requiringNew().run(()->em.createNativeQuery("INSERT INTO trilha(org_id,pendencia_id,tipo,ator) VALUES (?,?,?,'HUMANO:"+c.gestor+"')").setParameter(1,c.org).setParameter(2,p).setParameter(3,tipo).executeUpdate());}
 private Map<String,Object> h(Ctx c){return Map.of("X-Org-Id",c.org.toString(),"X-Pessoa-Id",c.gestor.toString());}private long num(String q,Object p){return QuarkusTransaction.requiringNew().call(()->((Number)em.createNativeQuery(q).setParameter(1,p).getSingleResult()).longValue());}private record Ctx(UUID org,UUID gestor){}
}
