import { Anchor, Badge, Button, Group, Paper, Select, SimpleGrid, Stack, Text, TextInput, Title } from "@mantine/core";
import { useQuery } from "@tanstack/react-query";
import { useState } from "react";
import { buscarItens, detalheItem, listarPessoasConsulta, type ItemConsultaCompleta } from "../api/itens";
import { corClasse, rotulo } from "../util/rotulos";

export function ItensPage(){const [q,setQ]=useState("");const [status,setStatus]=useState<string|null>(null);const [classe,setClasse]=useState<string|null>(null);const [nivel,setNivel]=useState<string|null>(null);const [pessoaId,setPessoaId]=useState<string|null>(null);const [de,setDe]=useState("");const [ate,setAte]=useState("");const [origem,setOrigem]=useState("");const [pagina,setPagina]=useState(0);const [aberto,setAberto]=useState<string|null>(null);
 const params:Record<string,string>={pagina:String(pagina),tamanho:"25"};if(q)params.q=q;if(status)params.status=status;if(classe)params.classe=classe;if(nivel)params.nivel=nivel;if(pessoaId)params.pessoaId=pessoaId;if(de)params.de=new Date(`${de}T00:00:00`).toISOString();if(ate)params.ate=new Date(`${ate}T23:59:59`).toISOString();if(origem)params.origem=origem;
 const {data,isLoading}=useQuery({queryKey:["itens",params],queryFn:()=>buscarItens(params)});
 const pessoas=useQuery({queryKey:["pessoas-consulta"],queryFn:listarPessoasConsulta});const opcoesPessoas=pessoas.data?.map(p=>({value:p.id,label:p.nome}))??[];
 return <Stack><div><Title order={2}>Itens e decisões</Title><Text c="dimmed" size="sm">Consulta histórica. As ações continuam na Entrada, no bloco ou com o executor.</Text></div>
 <Paper p="md"><SimpleGrid cols={{base:1,sm:2,lg:4}}><TextInput aria-label="buscar itens" placeholder="Título, contraparte, origem ou executor" value={q} onChange={e=>{setQ(e.currentTarget.value);setPagina(0)}}/><Select aria-label="estado" placeholder="Todos os estados" clearable data={["ENTRADA","DELEGADA","AGENDADA","DORMINDO","FECHADA"]} value={status} onChange={v=>{setStatus(v);setPagina(0)}}/><Select aria-label="classe" placeholder="Todas as classes" clearable data={["DECISAO","BLOQUEIO","ESTEIRA"]} value={classe} onChange={v=>{setClasse(v);setPagina(0)}}/><Select aria-label="nível" placeholder="Todos os níveis" clearable data={["N1","N2","N3"]} value={nivel} onChange={v=>{setNivel(v);setPagina(0)}}/><Select aria-label="pessoa" placeholder="Qualquer pessoa" searchable clearable data={opcoesPessoas} value={pessoaId} onChange={v=>{setPessoaId(v);setPagina(0)}}/><TextInput aria-label="desde" type="date" value={de} onChange={e=>{setDe(e.currentTarget.value);setPagina(0)}}/><TextInput aria-label="até" type="date" value={ate} onChange={e=>{setAte(e.currentTarget.value);setPagina(0)}}/><TextInput aria-label="origem" placeholder="Origem" value={origem} onChange={e=>{setOrigem(e.currentTarget.value);setPagina(0)}}/></SimpleGrid></Paper>
 {isLoading&&<Text c="dimmed">Consultando…</Text>}{data?.itens.map(i=><Item key={i.id} item={i} aberto={aberto===i.id} alternar={()=>setAberto(aberto===i.id?null:i.id)}/>)}
 {data&&data.itens.length===0&&<Paper p="lg"><Text c="dimmed">Nenhum item encontrado.</Text></Paper>}
 {data&&<Group justify="space-between"><Text size="sm" c="dimmed">{data.total} resultado(s)</Text><Group><Button variant="default" disabled={pagina===0} onClick={()=>setPagina(p=>p-1)}>Anterior</Button><Button variant="default" disabled={(pagina+1)*25>=data.total} onClick={()=>setPagina(p=>p+1)}>Próxima</Button></Group></Group>}
 </Stack>}
function Item({item,aberto,alternar}:{item:ItemConsultaCompleta;aberto:boolean;alternar:()=>void}){const d=useQuery({queryKey:["item",item.id],queryFn:()=>detalheItem(item.id),enabled:aberto});return <Paper p="md" data-testid="item-consulta"><Group justify="space-between" align="start"><Stack gap={4}><Group><Badge color={corClasse(item.classe)}>{rotulo(item.classe)}</Badge><Badge variant="outline">{item.status}</Badge>{item.nivel&&<Badge variant="light">{item.nivel}</Badge>}</Group><Text fw={600}>{item.titulo}</Text><Text size="sm" c="dimmed">{[item.executor,item.origem,item.quemEspera].filter(Boolean).join(" · ")||"Sem contraparte reconhecida"}</Text></Stack><Button variant="subtle" onClick={alternar}>{aberto?"Fechar história":"Ver história"}</Button></Group>{aberto&&<Stack mt="md" gap="xs"><Group>{item.links.filter(l=>l.tipo!=="TRILHA").map(l=><Anchor key={l.tipo} href={l.href}>{l.tipo.toLowerCase()}</Anchor>)}</Group>{d.data?.trilha.map((e,n)=><Paper key={n} p="xs" withBorder><Text size="sm" fw={500}>{e.tipo}</Text><Text size="xs" c="dimmed">{new Date(e.ocorridoEm).toLocaleString("pt-BR")} · {e.ator}</Text></Paper>)}</Stack>}</Paper>}
